"""Markdown 日报生成。"""

import os
from collections import Counter
from datetime import datetime
from typing import Any


class DailyReporter:
    def __init__(self, config: dict[str, Any]):
        self.report_dir = config["output"]["report_dir"]
        self.date_format = config["output"]["date_format"]

    def generate(self, repos: list[dict[str, Any]]) -> str:
        """生成日报并写入文件，返回文件路径。"""
        today = datetime.now().strftime(self.date_format)
        os.makedirs(self.report_dir, exist_ok=True)
        filepath = os.path.join(self.report_dir, f"{today}.md")

        content = self._render(today, repos)
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(content)

        return filepath

    def _render(self, today: str, repos: list[dict[str, Any]]) -> str:
        lines: list[str] = []
        lines.append(f"# AI Hunter Daily — {today}")
        lines.append("")
        lines.append(f"> 每日自动挖掘 GitHub 上新兴的 AI Agent / Skill / AI 工具项目。共发现 **{len(repos)}** 个候选项目。")
        lines.append("")

        # 汇总
        if repos:
            top_repo = repos[0]
            total_stars = sum(r["stars"] for r in repos)
            total_forks = sum(r["forks"] for r in repos)
            lines.append("## 📊 今日汇总")
            lines.append("")
            lines.append(f"- 🏆 最高分项目：[{top_repo['full_name']}]({top_repo['html_url']})（{top_repo['total_score']:.1f} 分）")
            lines.append(f"- ⭐ 累计 Stars：{total_stars:,}")
            lines.append(f"- 🍴 累计 Forks：{total_forks:,}")
            lines.append("")

            # 标签云
            all_topics: list[str] = []
            for r in repos:
                all_topics.extend(r.get("topics", []))
            if all_topics:
                top_topics = Counter(all_topics).most_common(15)
                lines.append("### 🔥 热门标签")
                lines.append("")
                lines.append(", ".join(f"`{t}` ({c})" for t, c in top_topics))
                lines.append("")

        # 项目列表
        lines.append("## 🚀 候选项目")
        lines.append("")

        for idx, repo in enumerate(repos, start=1):
            lines.extend(self._render_repo(idx, repo))

        lines.append("---")
        lines.append("")
        lines.append(f"*Generated by AI Hunter Daily at {datetime.now().isoformat(timespec='minutes')}*")
        lines.append("")

        return "\n".join(lines)

    def _render_repo(self, idx: int, repo: dict[str, Any]) -> list[str]:
        lines: list[str] = []
        lines.append(f"### {idx}. [{repo['full_name']}]({repo['html_url']})")
        lines.append("")

        desc = repo.get("description") or "暂无描述"
        lines.append(f"{desc}")
        lines.append("")

        lines.append("| 指标 | 数值 |")
        lines.append("|------|------|")
        lines.append(f"| ⭐ Stars | {repo['stars']:,} |")
        lines.append(f"| 🍴 Forks | {repo['forks']:,} |")
        lines.append(f"| 👀 Watchers | {repo['watchers']:,} |")
        lines.append(f"| 📅 创建时间 | {repo['created_at'][:10] if repo['created_at'] else '-'} |")
        lines.append(f"| 🔄 最近推送 | {repo['pushed_at'][:10] if repo['pushed_at'] else '-'} |")
        lines.append(f"| 🌐 主要语言 | {repo.get('language', 'Unknown')} |")
        lines.append(f"| 📈 日均 Star | {repo.get('star_velocity', 0):.2f} |")
        lines.append(f"| 🎯 综合得分 | **{repo['total_score']:.1f}** |")
        lines.append("")

        if repo.get("topics"):
            lines.append(f"**Tags**：{', '.join(f'`{t}`' for t in repo['topics'][:8])}")
            lines.append("")

        lines.append(f"**推荐理由**：{repo.get('recommendation', '')}")
        lines.append("")
        return lines
